var CC13 = {"decisions": [

{   "id":1,
   text:"  La loi organique qui modifie les dispositions de l'ordonnance du 29 décembre 1958 modifiée, portant loi organique relative au Conseil économique et social, en ce qui concerne le délai imparti au Conseil pour donner son avis lorsque l'urgence est déclarée par le Gouvernement, la répartition des sièges attribués aux diverses catégories socio-professionnelles, le nombre, la composition et les compétences des sections d'études, le nombre des membres du bureau, l'organisation des activités de l'assemblée, la publicité des séances et supprime les références à la Communauté contenues dans l'ordonnance du 29 décembre 1958 n'est pas contraire à la Constitution. (84-171 DC, 18 juin 1984, sol. imp., Journal officiel du 20 juin 1984, page 1896, Rec. p. 19)",
   type:"DC",
   item_label:"Généralités",
   item_num:"13a1a1",
   url:"http://www.conseil-constitutionnel.fr/decision/1984/84171DC.htm",
   number:"84-171 DC"}
,
{   "id":2,
   text:" L'article unique de la loi organique proroge la durée du mandat des membres du Conseil économique, social et environnemental jusqu'à l'expiration d'un délai de quatre mois suivant la promulgation de la loi organique modifiant la composition du Conseil pour l'application de la loi constitutionnelle du 23 juillet 2008 susvisée et, en tout état de cause, au plus tard jusqu'au 30 septembre 2010. Cette prorogation du mandat de cinq ans prévu par l'article 9 de l'ordonnance organique du 29 décembre 1958 susvisée, qui est limitée et revêt un caractère exceptionnel et transitoire, n'est pas contraire à la Constitution. (2009-586 DC, 30 juillet 2009, cons. 2, Journal officiel du 5 août 2009, page 13053, texte n° 3, Rec. p. 150)",
   type:"DC",
   item_label:"Généralités",
   item_num:"13a1a1",
   url:"http://www.conseil-constitutionnel.fr/decision/2009/2009586DC.htm",
   number:"2009-586 DC"}
,
{   "id":3,
   text:" La loi organique ayant pour objet, d'une part, de porter de huit à neuf sièges la représentation des activités économiques et sociales d'outre-mer au sein du Conseil économique et social et, d'autre part, d'inclure dans cette représentation, outre les départements et territoires d'outre-mer, ' les collectivités territoriales à statut particulier d'outre-mer ' est conforme à la Constitution. (90-279 DC, 7 novembre 1990, sol. imp., Journal officiel du 9 novembre 1990, page 13716, Rec. p. 77)",
   type:"DC",
   item_label:"Composition",
   item_num:"13a1a2",
   url:"http://www.conseil-constitutionnel.fr/decision/1990/90279DC.htm",
   number:"90-279 DC"}
,
{   "id":4,
   text:" Relèvent du domaine d'intervention de la loi organique les dispositions relatives à la composition du bureau du Conseil économique et social ainsi qu'aux modalités selon lesquelles sont prises les décisions concernant l'administration de son personnel. (92-310 DC, 29 juillet 1992, cons. 2 et 3, Journal officiel du 31 juillet 1992, page 10335, Rec. p. 71)",
   type:"DC",
   item_label:"Composition",
   item_num:"13a1a2",
   url:"http://www.conseil-constitutionnel.fr/decision/1992/92310DC.htm",
   number:"92-310 DC"}
,
{   "id":5,
   text:" La modification de la composition du Conseil économique et social afin de prendre en compte la création des collectivités de Saint-Barthélemy et de Saint-Martin n'est pas contraire à la Constitution et notamment à son article 71. (2007-547 DC, 15 février 2007, cons. 19 et 20, Journal officiel du 22 février 2007, page 3252, texte n° 3, Rec. p. 60)",
   type:"DC",
   item_label:"Composition",
   item_num:"13a1a2",
   url:"http://www.conseil-constitutionnel.fr/decision/2007/2007547DC.htm",
   number:"2007-547 DC"}
,
{   "id":6,
   text:" L'article 7 de la loi organique relative au Conseil économique, social et environnemental modifie la composition de ce dernier, dans la limite fixée par l'article 71 de la Constitution, afin notamment d'y faire siéger des personnes au titre de la protection de la nature et de l'environnement. Il tend également à favoriser la place des femmes dans cette institution sur le fondement du second alinéa de l'article 1er de la Constitution. Son article 9 limite à deux le nombre de mandats successifs qui pourront être exercés par les membres et complète les dispositions relatives à leur remplacement en cas de vacance. Ces dispositions sont conformes à la Constitution. ( 2010-608 DC, 24 juin 2010, cons. 5 à 7, Journal officiel du 29 juin 2010, page 11635, texte n° 2, Rec. p. 124)",
   type:"DC",
   item_label:"Composition",
   item_num:"13a1a2",
   url:"http://www.conseil-constitutionnel.fr/decision//2010608DC.htm",
   number:"2010-608 DC"}
,
{   "id":7,
   text:" Seule la loi organique fixe le régime des incompatibilités applicables aux membres du Conseil économique et social. Une loi qui n'a pas le caractère organique ne peut instituer un nouveau cas d'incompatibilité. (84-177 DC, 30 août 1984, cons. 6, Journal officiel du 4 septembre 1984, page 2803, Rec. p. 66) (84-178 DC, 30 août 1984, cons. 7, Journal officiel du 4 septembre 1984, page 2804, Rec. p. 69)",
   type:"DC",
   item_label:"Incompatibilités",
   item_num:"13a2a1",
   url:"http://www.conseil-constitutionnel.fr/decision/1984/84177DC.htm",
   number:"84-177 DC"}
,
{   "id":8,
   text:" L'article 8 de la loi organique relative au Conseil économique, social et environnemental complète l'article 7-1 de l'ordonnance n° 58-1360 du 29 décembre 1958 afin de préciser que le mandat de sénateur est incompatible avec la qualité de membre du Conseil économique, social et environnemental. Cette incompatibilité résulte déjà de la combinaison de l'article 7-1 précité avec les articles L.O. 139 et L.O. 297 du code électoral. Le Conseil constitutionnel a déclaré ces dispositions conformes à la Constitution dans ses décisions n° 85-205 DC du 28 décembre 1985 et n° 2000-427 DC du 30 mars 2000. Non-lieu à procéder à un nouvel examen de cette incompatibilité. (2010-608 DC, 24 juin 2010, cons. 2, Journal officiel du 29 juin 2010, page 11635, texte n° 2, Rec. p. 124)",
   type:"DC",
   item_label:"Incompatibilités",
   item_num:"13a2a1",
   url:"http://www.conseil-constitutionnel.fr/decision/2010/85205DC.htm",
   number:"85-205 DC"}
,
{   "id":9,
   text:" L'article 10 de la loi organique relative au Conseil économique, social et environnemental prévoit qu'à l'issue d'une période de quatre ans puis tous les dix ans, le Gouvernement remet au Parlement, après avis du Conseil économique, social et environnemental, un rapport relatif à l'actualisation de sa composition. Il dispose que ce rapport doit faire l'objet d'un débat devant le Parlement. D'une part, en subordonnant le dépôt de ce rapport à un avis du Conseil économique, social et environnemental, il méconnaît le champ de compétence de ce dernier tel que défini par les articles 69 et 70 de la Constitution. D'autre part, en exigeant un débat devant le Parlement sur ce rapport, il porte atteinte aux modalités de fixation de l'ordre du jour des assemblées parlementaires telles que déterminées par l'article 48 de la Constitution. Par suite, il est contraire à la Constitution. (2010-608 DC, 24 juin 2010, cons. 10, Journal officiel du 29 juin 2010, page 11635, texte n° 2, Rec. p. 124)",
   type:"DC",
   item_label:"Consultation obligatoire",
   item_num:"13a3a1",
   url:"http://www.conseil-constitutionnel.fr/decision/2010/2010608DC.htm",
   number:"2010-608 DC"}
,
{   "id":10,
   text:"  Il y a lieu d'entendre par ' loi de programme à caractère économique et social ' qui, en vertu de l'article 70 de la Constitution, est soumise pour avis au Conseil économique et social, une loi qui, non seulement définit des objectifs à moyen ou long terme en matière économique et sociale, mais comporte, en outre, des prévisions de dépenses chiffrées pour la réalisation de ces objectifs. (86-207 DC, 26 juin 1986, cons. 7, Journal officiel du 27 juin 1986, page 7978, Rec. p. 61)",
   type:"DC",
   item_label:"Notion de loi de programme à caractère économique et social",
   item_num:"13a3a1a1a1",
   url:"http://www.conseil-constitutionnel.fr/decision/1986/86207DC.htm",
   number:"86-207 DC"}
,
{   "id":11,
   text:" Si la loi autorisant le Gouvernement à prendre diverses mesures d'ordre économique et social se réfère à certains objectifs de caractère économique et social proposés par le Gouvernement, elle ne comporte aucune prévision de dépenses chiffrées. En conséquence, le vote de cette loi ne devait pas être précédé de la consultation du Conseil économique et social, même s'il eût été loisible au Gouvernement de procéder à la consultation de cet organisme en application de l'article 2, alinéa 4, de l'ordonnance n° 58-1360 du 29 décembre 1958 portant loi organique relative au Conseil économique et social. (86-207 DC, 26 juin 1986, cons. 8, Journal officiel du 27 juin 1986, page 7978, Rec. p. 61)",
   type:"DC",
   item_label:"Notion de loi de programme à caractère économique et social",
   item_num:"13a3a1a1a1",
   url:"http://www.conseil-constitutionnel.fr/decision/1986/86207DC.htm",
   number:"86-207 DC"}
,
{   "id":12,
   text:" Aux termes de l'avant-dernier alinéa de l'article 34 de la Constitution, ' des lois de programme déterminent les objectifs de l'action économique et sociale de l'État '. L'article 1er de l'ordonnance du 2 janvier 1959, qui prévoyait que ' les autorisations de programme peuvent être groupées dans des lois dites 'lois de programme ', a été abrogé à compter du 1er janvier 2005 par la loi organique du 1er août 2001 relative aux lois de finances. L'article 70 de la Constitution dispose que ' tout projet de loi de programme à caractère économique ou social ' est soumis pour avis au Conseil économique et social. En vertu des dispositions combinées du dernier alinéa de l'article 1er de l'ordonnance du 2 janvier 1959 et des articles 34 et 70 de la Constitution, devait être entendue, avant le 1er janvier 2005, comme ' loi de programme à caractère économique ou social ', une loi qui, non seulement définissait des objectifs à moyen ou long terme en matière économique et sociale, mais comportait, en outre, des prévisions de dépenses chiffrées pour la réalisation de ces objectifs. À la date du dépôt du projet dont est issue la loi déférée sur le bureau de la première assemblée saisie, qui est antérieure à l'abrogation de l'article 1er de l'ordonnance du 2 janvier 1959, celui-ci ne comportait pas de prévisions de dépenses chiffrées et n'avait donc pas le caractère d'un projet de loi de programme. Dès lors, le Gouvernement n'était pas tenu de le soumettre pour avis au Conseil économique et social. (2003-474 DC, 17 juillet 2003, cons. 11, Journal officiel du 22 juillet 2003, page 12336, Rec. p. 389) (2005-516 DC, 7 juillet 2005, cons. 5 et 6, Journal officiel du 14 juillet 2005, page 11589, texte n° 3, Rec. p. 102)",
   type:"DC",
   item_label:"Notion de loi de programme à caractère économique et social",
   item_num:"13a3a1a1a1",
   url:"http://www.conseil-constitutionnel.fr/decision/2003/2003474DC.htm",
   number:"2003-474 DC"}
,
{   "id":13,
   text:" Aux termes de l'avant-dernier alinéa de l'article 34 de la Constitution, ' des lois de programme déterminent les objectifs de l'action économique et sociale de l'État '. La loi organique du 1er août 2001 relative aux lois de finances a abrogé l'article 1er de l'ordonnance du 2 janvier 1959 qui prévoyait que ' les autorisations de programme peuvent être groupées dans des lois dites 'lois de programme '. En vertu de l'article 70 de la Constitution, ' tout projet de loi de programme à caractère économique ou social ' est soumis pour avis au Conseil économique et social. Le rapport annexé à la loi déférée fixe des objectifs à l'action de l'État dans le domaine de l'enseignement. Ses dispositions sont de celles qui peuvent trouver leur place dans la catégorie des lois de programme à caractère économique ou social prévue par l'avant-dernier alinéa de l'article 34 de la Constitution. Néanmoins, s'il était loisible au Gouvernement d'associer le Parlement à la politique qu'il entend mettre en oeuvre dans le domaine de l'éducation par une loi de programme, il devait, dès lors, respecter la procédure prévue à cet effet. En l'espèce, dès le dépôt sur le bureau de la première assemblée saisie du projet dont est issue la loi déférée, le rapport annexé à celle-ci se rattachait à la catégorie des lois de programme. En effet, bien qu'ayant fait l'objet de nombreux amendements parlementaires au cours de son examen, il a toujours eu pour objet de faire approuver par le Parlement des dispositions dénuées d'effet juridique, mais fixant des objectifs qualitatifs et quantitatifs à l'action de l'État en matière éducative. Dès lors, en vertu de l'article 70 de la Constitution, il aurait dû être soumis pour avis au Conseil économique et social. L'omission de cette formalité substantielle a entaché la régularité de la procédure mise en oeuvre pour son approbation. Il s'ensuit que l'article 12 de la loi déférée, qui approuve le rapport annexé, est contraire à la Constitution. (2005-512 DC, 21 avril 2005, cons. 10 et 12 à 15, Journal officiel du 24 avril 2005, page 7173, texte n° 2, Rec. p. 72)",
   type:"DC",
   item_label:"Obligation de consultation",
   item_num:"13a3a1a1a2",
   url:"http://www.conseil-constitutionnel.fr/decision/2005/2005512DC.htm",
   number:"2005-512 DC"}
,
{   "id":14,
   text:" Aux termes du dernier alinéa de l'article 69 de la Constitution : ' Le Conseil économique, social et environnemental peut être saisi par voie de pétition dans les conditions fixées par une loi organique. Après examen de la pétition, il fait connaître au Gouvernement et au Parlement les suites qu'il propose d'y donner '. L'article 5 de la loi organique relative au Conseil économique, social et environnemental insère dans l'ordonnance n° 58-1360 du 29 décembre 1958 un article 4-1 qui organise le droit de pétition prévu par les dispositions précitées. Cet article exige notamment que la pétition porte sur une question à caractère économique, social ou environnemental, qu'elle soit rédigée en français, qu'elle soit signée par au moins 500 000 personnes majeures, de nationalité française ou résidant régulièrement en France, qu'elle soit déclarée recevable par le bureau du Conseil économique, social et environnemental, qu'elle fasse ensuite l'objet d'un avis en assemblée plénière dans le délai d'un an et, enfin, que cet avis soit adressé au Premier ministre, au président de l'Assemblée nationale et au président du Sénat, et publié au Journal officiel. Ces dispositions ne sont pas contraires à la Constitution. (2010-608 DC, 24 juin 2010, cons. 3 et 4, Journal officiel du 29 juin 2010, page 11635, texte n° 2, Rec. p. 124)",
   type:"DC",
   item_label:"Consultation par voie de pétition",
   item_num:"13a3a3",
   url:"http://www.conseil-constitutionnel.fr/decision/2010/2010608DC.htm",
   number:"2010-608 DC"}
]}
